name: CI

on:
  create:
    tags:
      - 'release-[0-9]{8}-[0-9]{1,2}'
  push:
    tags:
      - 'develop'
env:
  TAG_NAME: ${{ github.ref_name }}
  ENV_DEPLOY: ${{ github.ref_name == 'develop' && 'dev' || 'prod' }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2