name: CI
on:
  push:
    tags:
      - 'develop'
      - 'release-[0-9]{8}-[0-9]{1,2}'

env:
  TAG_NAME: ${{ github.ref_name }}
  ENV_DEPLOY: ${{ github.ref_name == 'develop' && 'dev' || 'prod' }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Print ENV_DEPLOY
        run: echo "ENV_DEPLOY is $ENV_DEPLOY"